In [10]:
import numpy as np
import numpy.linalg as lg

In [23]:
A = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 2]])

In [21]:
A0 = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 2]])

In [13]:
A1 = lg.inv(A)

In [14]:
B = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]])

In [15]:
A1.dot(B)

array([[0. , 1. , 0. ],
       [0.5, 0. , 0.5],
       [0. , 0.5, 0. ]])

In [16]:
A1.dot(np.array([2, 4, 3]))

array([2. , 2. , 1.5])

In [24]:
lg.eigvals(A)

array([3.2469796 , 0.19806226, 1.55495813])